#!/usr/bin/env python3
"""Measure and plot per-operation CUDA latency for the Transformer paths."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROJECT_DIR = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    from .operation_profile import OperationResult, run_operation_profile
except ImportError:
    from operation_profile import OperationResult, run_operation_profile  # type: ignore[no-redef]
from tiktok.lab import TransformerConfig


def build_profile_cases() -> tuple[tuple[str, TransformerConfig], ...]:
    # One block is profiled because the operation costs are independent of the
    # number of repeated layers.  The dimensions cover the benchmark regimes.
    return (
        ("small B1S32D128", TransformerConfig(1, 32, 128, 4, 512, 1, False)),
        ("default B8S128D512", TransformerConfig(8, 128, 512, 8, 2048, 1, False)),
        ("batch B4S64D512", TransformerConfig(4, 64, 512, 8, 2048, 1, False)),
        ("long B2S512D512", TransformerConfig(2, 512, 512, 8, 2048, 1, False)),
        ("wide B4S128D1024", TransformerConfig(4, 128, 1024, 16, 4096, 1, False)),
    )


def write_outputs(output_dir: Path, results: list[OperationResult]) -> None:
    csv_path = output_dir / "operation_profile_results.csv"
    image_path = output_dir / "operation_profile.png"
    report_path = output_dir / "OPERATION_PROFILE_REPORT.md"
    fields = [
        "shape", "setup", "operation", "baseline_ms", "optimized_ms",
        "speedup", "baseline_fraction", "optimized_fraction",
    ]
    with csv_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for result in results:
            writer.writerow({
                "shape": result.shape,
                "setup": result.setup,
                "operation": result.operation,
                "baseline_ms": f"{result.baseline_ms:.6f}",
                "optimized_ms": f"{result.optimized_ms:.6f}",
                "speedup": f"{result.speedup:.3f}",
                "baseline_fraction": f"{result.baseline_fraction:.4f}",
                "optimized_fraction": f"{result.optimized_fraction:.4f}",
            })

    shapes = []
    operations = []
    for result in results:
        if result.shape not in shapes:
            shapes.append(result.shape)
        if result.operation not in operations:
            operations.append(result.operation)
    baseline = np.array([
        [next(r.baseline_ms for r in results if r.shape == shape and r.operation == op)
         for op in operations] for shape in shapes
    ])
    optimized = np.array([
        [next(r.optimized_ms for r in results if r.shape == shape and r.operation == op)
         for op in operations] for shape in shapes
    ])
    x = np.arange(len(operations))
    width = 0.38
    fig, axes = plt.subplots(2, 1, figsize=(15, 10), constrained_layout=True)
    axes[0].bar(x - width / 2, baseline.mean(axis=0), width, color="#377eb8", label="baseline mean")
    axes[0].bar(x + width / 2, optimized.mean(axis=0), width, color="#4daf4a", label="optimized mean")
    axes[0].set_xticks(x, operations, rotation=25, ha="right")
    axes[0].set_ylabel("mean CUDA time per operation (ms)")
    axes[0].set_title("Mean operation latency across profiled shapes")
    axes[0].legend()
    speedups = optimized / baseline
    im = axes[1].imshow(speedups, cmap="RdYlGn_r", aspect="auto", vmin=float(speedups.min()), vmax=float(speedups.max()))
    axes[1].set_xticks(np.arange(len(operations)), operations, rotation=25, ha="right")
    axes[1].set_yticks(np.arange(len(shapes)), shapes)
    axes[1].set_xlabel("operation")
    axes[1].set_ylabel("shape")
    axes[1].set_title("Optimized / baseline time (below 1.0 is faster)")
    for row in range(speedups.shape[0]):
        for col in range(speedups.shape[1]):
            axes[1].text(col, row, f"{speedups[row, col]:.2f}", ha="center", va="center", fontsize=8)
    fig.colorbar(im, ax=axes[1], label="time ratio")
    fig.savefig(image_path, dpi=160, bbox_inches="tight")
    plt.close(fig)

    lines = [
        f"# Operation Profile ({len(shapes)} Shapes)", "",
        "Generated by `operation_profile_report.py` using CUDA events after warmup. Each operation is measured independently on identical tensors and weights; the numbers are not profiler traces.", "",
        "![Operation profile](operation_profile.png)", "",
        "## Interpretation", "",
    ]
    for shape in shapes:
        rows = [r for r in results if r.shape == shape]
        hotspot = max(rows, key=lambda r: r.baseline_fraction)
        best = min(rows, key=lambda r: r.optimized_ms / r.baseline_ms)
        lines.append(
            f"- **{shape}**: baseline hotspot is `{hotspot.operation}` ({hotspot.baseline_fraction * 100:.1f}% of isolated operation time); strongest measured reduction is `{best.operation}` at {best.speedup:.2f}× speedup."
        )
    lines += [
        "", "## Per-operation measurements", "",
        "| Shape | Operation | Baseline ms | Optimized ms | Speedup | Baseline share | Optimized share |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for result in results:
        lines.append(
            f"| {result.shape} | {result.operation} | {result.baseline_ms:.6f} | {result.optimized_ms:.6f} | {result.speedup:.3f}× | {result.baseline_fraction * 100:.1f}% | {result.optimized_fraction * 100:.1f}% |"
        )
    lines += [
        "", "## Optimization plan", "",
        "1. Keep SDPA as the attention implementation: the profiler verifies a fused CUTLASS FMHA kernel, while FlashAttention-2 shows that tiled online-softmax and work partitioning are the correct algorithmic target.",
        "2. Prioritize FFN GEMMs when they dominate: they are already dispatched to vendor GEMM; future work should test compiler/autotuned GEMM choices rather than replace them with an unvalidated custom kernel.",
        "3. Keep fused residual + LayerNorm only where its measured reduction exceeds launch overhead; the active model uses the 131,072-element shape gate.",
        "4. Treat QKV packing as a secondary win: it removes two projection launches, but its benefit is bounded by the GEMM arithmetic and layout cost.",
        "",
        "Raw data: `operation_profile_results.csv`.",
    ]
    report_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {csv_path}")
    print(f"wrote {image_path}")
    print(f"wrote {report_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=PROJECT_DIR)
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--repeats", type=int, default=40)
    args = parser.parse_args()
    results = run_operation_profile(build_profile_cases(), args.warmup, args.repeats)
    write_outputs(args.output_dir, results)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
